---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp
spec:
  serviceName: headless-service
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.12

---
apiVersion: v1
kind: Service
metadata:
  name: headless-service
spec:
  clusterIP: None      # <------ これが headless service に必須の設定
  ports:
    - name: "http-port"
      port: 80
      targetPort: 80
  selector:
    app: myapp
